### ISSUE TITLE
Review Notes

### ISSUE THREAD

**Issue by rx294** [mitre/eks-cis-node-baseline#1]
@wdower @ejaronne Please see below review notes for `eks-cis-node-baseline`

Consider grabbing `--kubeconfig` and `--config` files from kubelet service parameters rather than using input values.
the data can be grabbed using the `service` resource on `kubelet` service. 

Affected controls
- eks-cis-3.1.1
- eks-cis-3.1.2
- eks-cis-3.1.3
- eks-cis-3.1.4

The use of `kubectl proxy` to grab configs off API is not ideal to inspec test automation. This way requires the user to have the proxy shell running along on the remote target inspec it to be executed on.

Alternately the configs can be validated using the `kubelet` service flags using the `service` resource and parsing the kubelet config file.
The two checks describe above should be encased in a describe.one block since they are equally valid.

Affected controls:
- eks-cis-3.2.1
- eks-cis-3.2.10
- eks-cis-3.2.11
- eks-cis-3.2.2
- eks-cis-3.2.3
- eks-cis-3.2.4
- eks-cis-3.2.5
- eks-cis-3.2.6
- eks-cis-3.2.7
- eks-cis-3.2.9

Following check should be adapted to scan kubelet service definition over process flags since newer versions K8S does not reflect process flags on the running process.

Affected controls:
- eks-cis-3.2.8

**Comment by rx294** [comment]
Alternatively you could use the K8S resource pack library developed and publicly published at SD Gitlab repo.

https://gitlab.dsolab.io/scv-content/inspec/kubernetes/baselines/inspec-k8s-node

Pull the resource pack to the profile by setting the following in inspec.yml
```
depends:
  - name: inspec-k8s-node
    url: https://gitlab.dsolab.io/scv-content/inspec/kubernetes/baselines/inspec-k8s-node/-/archive/master/inspec-k8s-node-master.tar.gz

```

and use the resource as below

```
  describe.one do
    describe kubelet do
      its('read-only-port') { should cmp 0 }
    end

    describe kubelet_config_file do
      its('readOnlyPort') { should cmp 0 }
    end
  end

```

Example matching the profile use cases can be pulled from this profile 
https://gitlab.dsolab.io/scv-content/inspec/kubernetes/baselines/k8s-node-stig-baseline

**Comment by wdower** [comment]
I have updated the profile to use those dependencies.

**Comment by Amndeep7** [comment]
@wdower has this issue been resolved in full?

**Comment by wdower** [comment]
Yes, pardon me for the delay in closing it.
